{
    id: Integer,
    product_name: String,
    slogan: String,
    product_description: String,
    category: String,
    default_price: Integer,
    created_at: Date,
    updated_at: Date,
    features: Array,
    style_id: Integer,
    color: String,
    style_name: String,
    original_price: String,
    sale_price: String,
    default_style: Boolean,
    skus: Array,
    photos: Array,
    related: Array,
    feature: Array
}